export default {
  "en-US": {
    code: "en-US",
    lang: "English",
    timeZone: "America/New_York",
    flag: "us",
    currency: "USD",
  },
  "de-DE": {
    code: "de-DE",
    lang: "Deutsch",
    timeZone: "Europe/Berlin",
    flag: "de",
    currency: "EUR",
  },
  "zh-CN": {
    code: "zh-CN",
    lang: "中文简体",
    timeZone: "Asia/Shanghai",
    flag: "cn",
    currency: "CNY",
  },
  "zh-TW": {
    code: "zh-TW",
    lang: "台湾繁体",
    timeZone: "Asia/Taipei",
    flag: "tw",
    currency: "TWD",
  },
  "fr-FR": {
    code: "fr-FR",
    lang: "Français",
    timeZone: "Europe/Paris",
    flag: "fr",
    currency: "EUR",
  },
  "it-IT": {
    code: "it-IT",
    lang: "Italiano",
    timeZone: "Europe/Rome",
    flag: "it",
    currency: "EUR",
  },
  "ja-JP": {
    code: "ja-JP",
    lang: "日本語",
    timeZone: "Asia/Tokyo",
    flag: "jp",
    currency: "JPY",
  },
  "th-TH": {
    code: "th-TH",
    lang: "ไทย",
    timezone: "Asia/Bangkok",
    flag: "th",
    currency: "THB",
  },
  "pt-PT": {
    code: "pt-PT",
    lang: "Português",
    timeZone: "Europe/Lisbon",
    flag: "pt",
    currency: "EUR",
  },
  "es-ES": {
    code: "es-ES",
    lang: "Español",
    timeZone: "Europe/Madrid",
    flag: "es",
    currency: "EUR",
  },
  "ko-KR": {
    code: "ko-KR",
    lang: "한국의",
    timeZone: "Asia/Seoul",
    flag: "kr",
    currency: "KRW",
  },
  "tr-TR": {
    code: "tr-TR",
    lang: "Türkçe",
    timeZone: "Europe/Istanbul",
    flag: "tr",
    currency: "TRY",
  },
  "ar-IL": {
    code: "ar-IL",
    lang: "العربية",
    timezone: "Asia/Jerusalem",
    flag: "il",
    currency: "SAR",
  },
  "vi-VN": {
    code: "vi-VN",
    lang: "tiếng việt",
    timeZone: "Asia/Ho_Chi_Minh",
    flag: "vn",
    currency: "VND",
  },
  "ru-RU": {
    code: "ru-RU",
    lang: "Русский",
    timeZone: "Europe/Moscow",
    flag: "ru",
    currency: "RUB",
  },
  "en-GB": {
    code: "en-GB",
    lang: "English(United Kingdom)",
    timeZone: "Europe/London",
    flag: "gb",
    currency: "",
  },
  "en-AU": {
    code: "en-AU",
    lang: "English(Australia)",
    timeZone: "Australia/Sydney",
    flag: "au",
    currency: "",
  },
};
